package database





































































































































}	return count > 0, err	err := db.QueryRow("SELECT COUNT(1) FROM users WHERE "+field+" = ?", value).Scan(&count)	var count intfunc UserExists(db *sql.DB, field, value string) (bool, error) {}	return err	)`)		FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE		created_at TEXT NOT NULL,		token TEXT NOT NULL UNIQUE,		user_id INTEGER NOT NULL,		id INTEGER PRIMARY KEY AUTOINCREMENT,	_, err = d.Exec(`CREATE TABLE IF NOT EXISTS password_resets (	}		return err	if err != nil {	)`)		FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE		notify_comments INTEGER NOT NULL DEFAULT 1,		user_id INTEGER PRIMARY KEY,	_, err = d.Exec(`CREATE TABLE IF NOT EXISTS user_prefs (	}		return err	if err != nil {	)`)		FOREIGN KEY(image_id) REFERENCES images(id) ON DELETE CASCADE		FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,		created_at TEXT NOT NULL,		body TEXT NOT NULL,		image_id INTEGER NOT NULL,		user_id INTEGER NOT NULL,		id INTEGER PRIMARY KEY AUTOINCREMENT,	_, err = d.Exec(`CREATE TABLE IF NOT EXISTS comments (	}		return err	if err != nil {	)`)		FOREIGN KEY(image_id) REFERENCES images(id) ON DELETE CASCADE		FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,		UNIQUE(user_id, image_id),		created_at TEXT NOT NULL,		image_id INTEGER NOT NULL,		user_id INTEGER NOT NULL,		id INTEGER PRIMARY KEY AUTOINCREMENT,	_, err = d.Exec(`CREATE TABLE IF NOT EXISTS likes (	}		return err	if err != nil {	)`)		FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE		created_at TEXT NOT NULL,		path TEXT NOT NULL UNIQUE,		user_id INTEGER NOT NULL,		id INTEGER PRIMARY KEY AUTOINCREMENT,	_, err = d.Exec(`CREATE TABLE IF NOT EXISTS images (	}		return err	if err != nil {	)`)		created_at TEXT NOT NULL		path TEXT NOT NULL UNIQUE,		name TEXT NOT NULL,		id INTEGER PRIMARY KEY AUTOINCREMENT,	_, err = d.Exec(`CREATE TABLE IF NOT EXISTS assets (	}		return err	if err != nil {	)`)		FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE		created_at TEXT NOT NULL,		user_id INTEGER NOT NULL,		token TEXT PRIMARY KEY,	_, err = d.Exec(`CREATE TABLE IF NOT EXISTS sessions (	}		return err	if err != nil {	)`)		created_at TEXT NOT NULL		verify_token TEXT,		verified INTEGER NOT NULL DEFAULT 0,		password_hash TEXT NOT NULL,		email TEXT NOT NULL UNIQUE,		username TEXT NOT NULL UNIQUE,		id INTEGER PRIMARY KEY AUTOINCREMENT,	_, err := d.Exec(`CREATE TABLE IF NOT EXISTS users (func initSchema(d *sql.DB) error {}	return db	}		log.Fatalf("DB init schema error: %v", err)	if err = initSchema(db); err != nil {	db.SetMaxIdleConns(1)	db.SetMaxOpenConns(1)	db.SetConnMaxLifetime(0)	}		log.Fatalf("DB open error: %v", err)	if err != nil {	}		db, err = sql.Open("postgres", psqlInfo)			dbHost, dbPort, dbUser, dbPassword, dbName)		psqlInfo := fmt.Sprintf("host=%s port=%s user=%s password=%s dbname=%s sslmode=disable",	} else {		db, err = sql.Open("sqlite", "file:camagru.db?_pragma=journal_mode(WAL)&_pragma=foreign_keys(ON)")	if dbHost == "" {	dbName := os.Getenv("DB_NAME")	dbPassword := os.Getenv("DB_PASSWORD")	dbUser := os.Getenv("DB_USER")	dbPort := os.Getenv("DB_PORT")	dbHost := os.Getenv("DB_HOST")	var db *sql.DB	var err errorfunc InitDB() *sql.DB {)	_ "modernc.org/sqlite"	_ "github.com/lib/pq"	"os"	"log"	"fmt"	"database/sql"import (package database