package models







































}	return hex.EncodeToString(b), nil	}		return "", err	if _, err := rand.Read(b); err != nil {	b := make([]byte, n)func RandomToken(n int) (string, error) {}	return nil	}		return errors.New("Passwords do not match")	if password != confirm {	}		return errors.New("Password must be at least 8 characters")	if len(password) < 8 {	}		return errors.New("Invalid email address")	if !emailRe.MatchString(email) {	}		}			return errors.New("Username may contain letters, numbers, underscore")		if !(c == '_' || c >= '0' && c <= '9' || c >= 'a' && c <= 'z' || c >= 'A' && c <= 'Z') {	for _, c := range username {	}		return errors.New("Username must be 3-20 characters")	if len(username) < 3 || len(username) > 20 {func ValidateRegistration(username, email, password, confirm string) error {var emailRe = regexp.MustCompile(`^[^\s@]+@[^\s@]+\.[^\s@]+$`))	"regexp"	"errors"	"encoding/hex"	"crypto/rand"import (package models